### ISSUE TITLE
I am not seeing any file in library 

### ISSUE THREAD

**Issue by AshuMishra** [christianroman/Doppio#1]
Hello Chroman !
Hope you are doing good.

When I open the project there is 6-7 errors :
1- 'AFNetworking.h' file not found
2 : 'Mantle.h' file not found.etc. 
I am seeing that there is no file in Library folder. Please add it to project to work project effectively. 
Thanks

**Comment by christianroman** [comment]
Since the 'Libraries' subfolders are submodules you need to clone the repository in the right way with the next command.

`git clone --recursive https://github.com/chroman/Doppio.git`

If you already have the repo in your machine just use:

```
cd Doppio/Libraries
git submodule init
git submodule update
```

**Comment by AshuMishra** [comment]
Please provide instruction from step 1 because I am new in iOS. Where I have to execute this code in terminal or at other location?
